### ISSUE TITLE
KITTI SF: Downsample missing files

### ISSUE THREAD

**Issue by baurst** [vLAR-group/OGC#1]
Congratulations to your great work and thank you very much for releasing the code.

I am trying to run your project as described on the KITTI data (SF, Object, Semantic), but I am facing some trouble with the downsample_kitti.py script:

1. There are "too many values to unpack" in this line, I fixed it by using `pcs, segms, flows, _ = dataset[sid]`:
https://github.com/vLAR-group/OGC/blob/ab7a5badb95238f38dbf7b47bb29b238bcc1ec2c/data_prepare/kittisf/downsample_kittisf.py#L44
This will create the files in data up to `kitti_sf_downsampled/data/000099`, which brings me to the 2nd problem:

2. When I then try and run `train_seg.py config/seg/kittisf/kittisf_unsup_woinv.yaml --round 1` the first training epoch seems to run fine, but then I get an error - `kitti_sf_downsampled/data/000100/pc1.npy` can not be found.

> Caught FileNotFoundError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/lhome/baurst/anaconda3/envs/OGC/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/lhome/baurst/anaconda3/envs/OGC/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/lhome/baurst/anaconda3/envs/OGC/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/lhome/baurst/workspace/liflow2/OGC/datasets/dataset_kittisf.py", line 91, in __getitem__
>     pcs, segms, flows = self._load_data(idx, view_sel)
>   File "/lhome/baurst/workspace/liflow2/OGC/datasets/dataset_kittisf.py", line 67, in _load_data
>     pc1, pc2 = np.load(osp.join(data_path, 'pc%d.npy'%(view_id1 + 1))), np.load(osp.join(data_path, 'pc%d.npy'%(view_id2 + 1)))
>   File "/lhome/baurst/anaconda3/envs/OGC/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: '/path/to/kitti_sf_downsampled/data/000100/pc1.npy'
>   File "/lhome/baurst/workspace/liflow2/OGC/train_seg.py", line 97, in eval_epoch
>     for i, batch in tbar:
>   File "/lhome/baurst/workspace/liflow2/OGC/train_seg.py", line 192, in train
>     val_loss, val_avg, ap_eval_meter = self.eval_epoch(test_loader)
>   File "/lhome/baurst/workspace/liflow2/OGC/train_seg.py", line 350, in <module>
>     trainer.train(args.epochs, train_set, train_loader, val_loader)

Thanks in advance for taking a look & thank you for your help!
Best regards.

**Comment by Szy-Young** [comment]
Hi @baurst, thank you for your interest in our work and especially thank for helping us discovering this problem！

I have fixed it by setting the "view_sels". Now it should create data up to `kitti_sf_downsampled/data/000199`.

https://github.com/vLAR-group/OGC/blob/3afbf55159a795b8e483602dceedb4315817da43/data_prepare/kittisf/downsample_kittisf.py#L36-L41

**Comment by baurst** [comment]
Thank you very much for your quick response and quick fix! :)
