### ISSUE TITLE
您好这个代码能对大场景的点云适用吗，比如说S3DIS，多伦多3D

### ISSUE THREAD

**Issue by SC-shendazt** [vLAR-group/OGC#4]
您好这个代码能对大场景的点云适用吗，比如说S3DIS，多伦多3D

**Comment by Szy-Young** [comment]
您好 @SC-shendazt 
我们的算法本身不受场景大小的限制，计算资源足够即可。唯一的要求是训练样本中必须包含运动的物体，且运动物体占据的点的比例不能过少。因此静态室内场景的S3DIS是不适用的；Toronto 3D在训练前可能需要通过预处理筛选出包含有运动物体的帧。

**Comment by SC-shendazt** [comment]
> 您好 @SC-shendazt 我们的算法本身不受场景大小的限制，计算资源足够即可。唯一的要求是训练样本中必须包含运动的物体，且运动物体占据的点的比例不能过少。因此静态室内场景的S3DIS是不适用的；Toronto 3D在训练前可能需要通过预处理筛选出包含有运动物体的帧。

非常感谢您的快速回复，就是想测试一下室外用无人机拍摄的城市点云，但是好像基本上跟SIDIS类似，都是属于静态的建筑物，植被，汽车等，可能就不适合了。
