### ISSUE TITLE
geometric constraints

### ISSUE THREAD

**Issue by Alexanderisgod** [vLAR-group/OGC#5]
i view your video , it seems that your model often divides an object into two, or more, so the geometric constraints or loss designed is not perfect?
![image](https://user-images.githubusercontent.com/41862202/201921423-ca1b740c-e390-42e1-87e6-39efc69d4ba0.png)

**Comment by Szy-Young** [comment]
Hi @Alexanderisgod, the smoothness regularization in our method clusters neighboring points into the same object, thus avoids over-segmentation. This is a simple and effective solution, while we can expect better results from more advanced designs in the future, e.g., considering graph connectivity in the point cloud.

**Comment by Alexanderisgod** [comment]
> Hi @Alexanderisgod, the smoothness regularization in our method clusters neighboring points into the same object, thus avoids over-segmentation. This is a simple and effective solution, while we can expect better results from more advanced designs in the future, e.g., considering graph connectivity in the point cloud.

After reading your paper, I have to say that the design of the loss function is very instructive, but the generalization of the characteristics of moving objects to stationary objects is not enough using only the change of perspective.
