### ISSUE TITLE
On SemanticKITTI object segmentation

### ISSUE THREAD

**Issue by cama36** [vLAR-group/OGC#7]
Thank you very much for your work. I noticed that in the SemanticKITTI data set, you only segmented cars as the experimental results. I would like to ask if it is possible to carry out the experiment for all the SemanticKITTI objects in the paper?

**Comment by Szy-Young** [comment]
Hi @cama36, thanks for your interest in our work.

Our method learns from motions. Therefore in inference, we can only segment objects which we have seen moving in the training data. Many objects in SemanticKITTI, e.g., building, vegetation, are always static and segmenting them is beyond our scope.

**Comment by cama36** [comment]
ok,i get it,thank you very much!
