### ISSUE TITLE
SemanticKITTI Training

### ISSUE THREAD

**Issue by JudgeLJX** [vLAR-group/OGC#9]
Hi,

Thanks for your contribution.

Could you please tell me why there is no training part of SemanticKITTI?

Judy

**Comment by Szy-Young** [comment]
Hi @JudgeLJX ,

As described in our paper, for outdoor scenes, we only train on KITTI-SF dataset and directly test this well-trained model on SemanticKITTI.

**Comment by JudgeLJX** [comment]
Many thanks.
